apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: insurance-charges-model-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: insurance-charges-model-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75